spring:
    datasource:
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/foosball}
        username: ${DATASOURCE_USERNAME:postgres}
        password: ${DATASOURCE_PASSWORD:postgres}
    jpa:
      open-in-view: false
