# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      # DB parameters (arbitrary):
      DB_USER: circleci
      DB_NAME: foosball_test

    docker:
      # First of the images is used to run the commands in this file:
      - image: circleci/openjdk:11-jdk

      # Database for integration tests:
      - image: circleci/postgres:10.6
        environment:
          POSTGRES_USER: $DB_USER
          POSTGRES_DB: $DB_NAME

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Get Gradle dependencies
          command: gradle dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run:
          name: Wait for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

      - run:
          name: Run tests
          command: gradle check --info
          environment:
            DATASOURCE_URL: jdbc:postgresql://localhost:5432/$DB_NAME
            DATASOURCE_USERNAME: $DB_USER
            DATASOURCE_PASSWORD:
